using System;

namespace CPE.DapperIdentity.Abstractions
{
    /// <summary>
    /// The user shape the Dapper-backed stores read and write.
    /// </summary>
    /// <remarks>
    /// The string members are nullable because the columns behind them are: every column in the
    /// shipped <c>identityuser</c> schema is declared NULL, so a row can legitimately produce a null
    /// here. <c>Id</c> is the exception in intent - the model marks it as the key and the
    /// application always sets it - but it is left nullable to match the database, which declares it
    /// NULL with no primary key. Tightening that is a migration decision, not a type decision.
    /// </remarks>
    public interface ICustomIdentityUser
    {
        /// <summary>Primary key. Generated by the model's constructor when not supplied.</summary>
        public string? Id { get; set; }

        /// <summary>The login name.</summary>
        public string? UserName { get; set; }

        /// <summary>Upper-cased <see cref="UserName"/>, used for case-insensitive lookup.</summary>
        public string? NormalizedUserName { get; set; }

        /// <summary>The user's email address.</summary>
        public string? Email { get; set; }

        /// <summary>Upper-cased <see cref="Email"/>, used for case-insensitive lookup.</summary>
        public string? NormalizedEmail { get; set; }

        /// <summary>Whether the email address has been confirmed.</summary>
        public bool EmailConfirmed { get; set; }

        /// <summary>The hashed password. Never the password itself.</summary>
        public string? PasswordHash { get; set; }

        /// <summary>The user's phone number.</summary>
        public string? PhoneNumber { get; set; }

        /// <summary>Whether the phone number has been confirmed.</summary>
        public bool PhoneNumberConfirmed { get; set; }

        /// <summary>Whether two-factor authentication is enabled for this user.</summary>
        public bool TwoFactorEnabled { get; set; }

        /// <summary>Given name.</summary>
        public string? FirstName { get; set; }

        /// <summary>Family name.</summary>
        public string? LastName { get; set; }

        /// <summary>Changes when credentials change, invalidating issued tokens.</summary>
        public string? SecurityStamp { get; set; }

        /// <summary>Whether the account may sign in.</summary>
        public bool IsEnabled { get; set; }

        /// <summary>The current refresh token, if one has been issued.</summary>
        public string? RefreshToken { get; set; }

        /// <summary>When <see cref="RefreshToken"/> stops being accepted.</summary>
        public DateTime RefreshTokenExpireTime { get; set; }
    }
}
